spring:
  name: "Lucas JWT"
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    password: senac
    username: postgres
    driverClassName: org.postgresql.Driver
  security:
    token:
      secret: backendjwt
      expiration_time: tempo_expiracao
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: seu_email
    password: "senha_smtp"
    port: '587'